# Generated by Django 5.0.7 on 2024-07-11 21:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ted_talks", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="APIToken",
        ),
    ]
